/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOrderBookFactory1155,
  IOrderBookFactory1155Interface,
} from "../../../contracts/interfaces/IOrderBookFactory1155";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "Token1155",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "Token1155id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "Token20",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "createBook",
    outputs: [
      {
        internalType: "address",
        name: "book",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "Token1155",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "Token1155id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "Token20",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "getBook",
    outputs: [
      {
        internalType: "address",
        name: "book",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IOrderBookFactory1155__factory {
  static readonly abi = _abi;
  static createInterface(): IOrderBookFactory1155Interface {
    return new utils.Interface(_abi) as IOrderBookFactory1155Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOrderBookFactory1155 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IOrderBookFactory1155;
  }
}
